Models/Account.cs
namespace ChatX.Models
{
    public class Account
    {
        public int Id { get; set; }
        public string OpenIDIssuer { get; set; }
        public string OpenIDSubject { get; set; }
        public string Name { get; set; }
    }
}

Models/ChatRoom.cs
namespace ChatX.Models
{
    public class ChatRoom
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CreatedById { get; set; }
        public Account CreatedBy { get; set; }
        public bool IsDeleted { get; set; }

        public string GetRoomIdentifier() => $"{Id}{Name}"; 
    }
}

Models/DateMatch.cs
namespace ChatX.Models
{
    public class DateMatch
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public string PersonalityType { get; set; }
        public string Description { get; set; }
        public string[] UserInterests { get; set; }
        public string ProfileUrl { get; set; }
    }
}

Models/Emoji.cs
namespace ChatX.Models
{
    public class Emoji
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public Account Sender { get; set; }
    }
}

Models/Message.cs
namespace ChatX.Models
{
    public class Message
    {
        public int Id { get; set; }
        public Account Sender { get; set; }
        public string Content { get; set; }
        public DateTime TimeStamp { get; set; }
        public int? ChatRoomId { get; set; }
        public ChatRoom ChatRoom { get; set; }
        public bool IsDeleted { get; set; }
    }
}

Controllers/ChatController.cs
using ChatX.Data;
using ChatX.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ChatX.Controllers
{
    [Route("api")]
    [ApiController]
    [AllowAnonymous]
    public class ChatController : ControllerBase
    {
        private readonly AppDbContext _db;

        public ChatController(AppDbContext database)
        {
            _db = database;
        }

        [HttpGet("latest/{amount:int?}")]
        public ActionResult<List<Message>> GetLatestMessages(int? amount = null)
        {
            // If no amount is passed in, return 5 latest messages.
            int messageCount = amount ?? 5;

            var lastMessages = _db.Messages.Include(m => m.Sender)
                .Where(m => !m.IsDeleted)
                .OrderByDescending(m => m.Id)
                .Take(messageCount);

            if (!lastMessages.Any())
            {
                return NotFound();
            }

            return lastMessages.ToList();
        }
    }
}

Pages/DateFinder.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ChatX.Pages
{
    public class DateFinderModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ChatX.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/FakeLogin.cshtml.cs
using ChatX.Data;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace ChatX.Pages
{
    public class FakeLoginModel : PageModel
    {
        private readonly AppDbContext database;
        private readonly IWebHostEnvironment environment;

        public FakeLoginModel(AppDbContext database, IWebHostEnvironment environment)
        {
            this.database = database;
            this.environment = environment;
        }

        // Log in as the user with the specified account ID, without providing a password etc.
        // IMPORTANT: This should only be allowed in development, hence the if statement below.
        public async Task<IActionResult> OnPost(int accountID)
        {
            if (!environment.IsDevelopment())
            {
                return Forbid();
            }

            // Find the account in the database.
            var account = database.Accounts.Find(accountID);
            string subject = account.OpenIDSubject;
            string issuer = account.OpenIDIssuer;
            string name = account.Name;

            // Create the fake identity and principal objects needed to fake a login.
            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
            identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, subject, valueType: null, subject: identity, issuer: issuer, originalIssuer: null));
            identity.AddClaim(new Claim(ClaimTypes.Name, name, valueType: null, subject: identity, issuer: issuer, originalIssuer: null));
            var principal = new ClaimsPrincipal(identity);

            await HttpContext.SignInAsync(principal);

            return RedirectToPage("./Index");
        }
    }
}

Pages/Index.cshtml.cs
using ChatX.Data;
using ChatX.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Immutable;

namespace ChatX.Pages
{
    public class IndexModel : PageModel
    {
		public IActionResult OnPostRedirect()
		{
			return RedirectToPage("/DateFinder");
		}
	}
}

Pages/DateFinder.cshtml
@page
@using ChatX.Authentication;
@model ChatX.Pages.DateFinderModel
@inject AccessControl accessControl
@{
}

<div class="container">
    <h1><img src="~/js/MicrosoftTeams-image.png" /></h1>
    <h2>Date Finder</h2>
    <div class="list-container" v-for="message in dateBotMessages">
        <div id="userMsg" v-if="message.sender === @accessControl.LoggedInAccountID">
            <p><span class="username">@accessControl.LoggedInAccountName</span> {{ message.content }}</p>
        </div>
        <div id="msg" v-else>
            <p><span class="username">{{ message.sender.name }}</span> <span v-if="message.isHtml" v-html="message.content"></span>
                <span v-else>{{ message.content }}</span></p>
        </div>
    </div>
    <div id="input-container">
        <form v-on:submit.prevent="getDateMatch">
            <input class="messageInput" type="text" v-model="dateFinderInput" />
            <button class="buttons">Send</button>
        </form>
    </div>
</div>

Pages/FakeLogin.cshtml
@page
@model ChatX.Pages.FakeLoginModel
@{
}

Pages/Index.cshtml
@page
@using ChatX.Hubs;
@using ChatX.Authentication;
@model IndexModel
@inject AccessControl accessControl
@{
    ViewData["Title"] = "ChatX";
}

<div class="container">
    <h1><img src="~/js/MicrosoftTeams-image.png" /></h1>
    <div v-if="!connected">
        <p>Connecting to server...</p>
    </div>
    <div v-if="joinedRoomId === null">
        <h2>Available Chat Rooms</h2>
        <ul>
            <li class="chat-room" v-for="room in chatRooms" :key="room.id">
                <div class="room-text">
                    <p class="room-name">{{room.name}}</p>
                    <p class="created-by">Created by {{room.createdBy.name}}</p>
                </div>
                <div class="join-delete-room">
                    <button type="button" id="join-room-button" class="buttons" v-on:click="joinChatRoom(room.id)">Join</button>
                    <button type="button"
                            id="delete-room-button"
                            class="buttons"
                            v-if="room.createdBy.id === @accessControl.LoggedInAccountID"
                            v-on:click="deleteChatRoom(room.id)">
                        Delete
                    </button>
                </div>
            </li>
        </ul>
        <div>
            <form v-on:submit="createChatRoom">
                <label>Chatroom Name</label>
                <input class="messageInput" type="text" placeholder="Chat room name" v-model="newChatRoom" />
                <button class="buttons">Create Room</button>
            </form>
        </div>
        <form class="bot" method="post">
            <h3>DateBot - Find a Match Today!</h3>
            <button class="buttons" type="submit" asp-page-handler="Redirect">Go to DateBot!</button>
        </form>
    </div>
    <div v-else>
        <div class="list-container" v-for="message in messages" :key="message.id">
            <div id="userMsg" v-if="message.sender.id === @accessControl.LoggedInAccountID">
                <p><span class="username">@accessControl.LoggedInAccountName</span> {{ message.content }}</p>
                <button class="delete-mark" v-on:click="deleteMessage(message.id)"></button>
            </div>
            <div id="msg" v-else>
                <p><span class="username">{{ message.sender.name }}</span> {{ message.content }}</p>
            </div>
        </div>
        <div v-if="usersCurrentlyTyping.length > 0">
            <p class="currently-typing" v-if="usersCurrentlyTyping.length === 1">
                {{ usersCurrentlyTyping[0].name }} is typing...
            </p>
            <p class="currently-typing" v-else>Several people are typing...</p>
        </div>
        <div id="input-container">
            <form v-on:submit.prevent="sendMessage">
                <input class="messageInput" type="text" v-on:input="currentlyTyping" v-model="newMessage" v-bind:disabled="roomIsRemoved" />
                <button class="buttons" v-bind:disabled="roomIsRemoved">Send</button>
            </form>
            <button id="leave-button" class="buttons" v-on:click="leaveChatRoom">Leave Room</button>
            <div class="profile" v-for="profile in profiles">
                <p class="matchedProfile">You matched with: {{profile.firstName}} {{profile.lastName}} {{profile.age}}</p>
            </div>
        </div>
    </div>
</div>

Pages/Shared/Components/FakeLoginMenu/Default.cshtml
@using ChatX.Models;
@model IEnumerable<SelectListItem>;

<form method="post" asp-page="/FakeLogin">
    <label>
        Log in as:
        <select asp-items="@Model" name="AccountID" id="account-id"></select>
    </label>
    <button type="submit">Log In</button>
</form>

Pages/Shared/_Layout.cshtml
@using ChatX.Pages.Shared.Components.LoginMenu;
@using ChatX.Authentication;
@inject AccessControl accessControl

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true">
    <script src="~/js/chat.js" asp-append-version="true" defer></script>
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script>var loggedInUser = @accessControl.LoggedInAccountID</script>
    @await RenderSectionAsync("Scripts", required: false)
</head>
<body>
    <div id="app">
        <header>
            <environment names="Development">
                @await Component.InvokeAsync(nameof(FakeLoginMenu))
            </environment>
        </header>
        <main>
            @RenderBody()
        </main>
    </div>
</body>
</html>